### ISSUE TITLE
Logout after access token refresh causes side effects with CSRF tokens

### ISSUE THREAD

**Issue by Schille** [Blueshoe/pycloak#6]
This logic
https://github.com/Blueshoe/pycloak/blob/7fd19d06e035e498d6a7ef0cc62576da64f512cd/pycloak/middleware.py#L60-L65
causes filling forms (in Django admin for instance) for longer to be unusable since the CSRF token renders invalid in the short time of the JWT access token.

**Comment by tschale** [comment]
Until we fix it, we need to workaround and set the access token lifespan to multiple hours
